version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: url_shortener
      MYSQL_DATABASE: url_shortener
      MYSQL_USER: url_shortener
      MYSQL_PASSWORD: url_shortener
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "4306:3306"

  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/src
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/src
    depends_on:
      - php
      - mysql

volumes:
  mysql:
    name: mysql